name: syncplay
summary: Syncplay
version: build
version-script: cat syncplay/__init__.py | awk '/version/ {gsub("\047", "", $3); print $NF}'
summary: Client/server to synchronize media playback on many computers
description: |
  Syncplay synchronises the position and play state of multiple media players
  so that the viewers can watch the same thing at the same time. This means that
  when one person pauses/unpauses playback or seeks (jumps position) within their
  media player then this will be replicated across all media players connected to
  the same server and in the same 'room' (viewing session). When a new person
  joins they will also be synchronised. Syncplay also includes text-based chat so
  you can discuss a video as you watch it (or you could use third-party Voice over 
  IP software to talk over a video).

confinement: classic
icon: syncplay/resources/syncplay.png
grade: stable

parts:
  syncplay:
    plugin: python
    source: .
    stage-packages:
      - python3-pyside
    after: [desktop-qt4]

apps:
  syncplay:
    command: bin/desktop-launch $SNAP/usr/bin/python3 $SNAP/bin/syncplay
    desktop: lib/python3.5/site-packages/syncplay/resources/syncplay.desktop

  syncplay-server:
    command: bin/syncplay-server
    desktop: lib/python3.5/site-packages/syncplay/resources/syncplay-server.desktop
