#!/bin/sh

curl -L "https://dl.bintray.com/alby128/Syncplay/homebrew-cache.tar.gz" -o homebrew-cache.tar.gz
if [ -f homebrew-cache.tar.gz ]; then
  if ! tar tf homebrew-cache.tar.gz &>/dev/null; then
    rm homebrew-cache.tar.gz
    exit 0
  fi
  tar zxf homebrew-cache.tar.gz --directory /usr/local/Cellar
  brew unlink pkg-config
  brew link pkg-config
  brew link --force readline sqlite gdbm makedepend python@2
fi
