#!/bin/sh

curl -L "https://dl.bintray.com/alby128/Syncplay/python-cache.tar.gz" -o python-cache.tar.gz
if [ -f python-cache.tar.gz ]; then
  if ! tar tf python-cache.tar.gz &>/dev/null; then
    rm python-cache.tar.gz
    exit 0
  fi
  tar zxf python-cache.tar.gz --directory /usr/local/lib/python2.7
fi
